### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by carlkesselman** [technik-gegg/LeoNerd-OLED-Module-Library#2]
Hi,

Been using this library. Working great, thanks!

I noticed that you have defined an interface for doublclick, but it looks like it has not been implemented.  Wanted to confirm that this is the case.

Thanks,

Carl

**Comment by technik-gegg** [comment]
Hi Carl,

yes, this is correct. It's in there because of compatibility reasons to the solution I've used before. 
If you need a doubleclick, it would have to be implemented in the firmware, since that's the only instance that knows for sure about button states.
You may contact [GMagican](https://github.com/GMagician) on this behalf. He has successfully compiled his own firmware for this module which already comes with the benefit of an rotary encoder acceleration/deceleration and is fully compatible to the original one.
If you wanna try it out first, [here's a link](https://discordapp.com/channels/741179485474521110/782853119368232960/794230165109866506) where he has published his hex file.
